polarity = "dark"
[font.default]
name = "Inter Regular"
package = "inter"
[font.monospace]
name = "MesloLg NF"
package = "nerd-fonts.meslo-lg"
[cursor]
name = "Vimix-cursors"
package = "vimix-cursors"
size = 24
[icons]
name = "Papirus-Dark"
package = "papirus-icon-theme"
[colors]
base00 = "1a0608" # Default Background
base01 = "3B4252" # Lighter Background
base02 = "434C5E" # Selection Background
base03 = "4c566a" # Comments, Invisibles, Line Highlighting
base04 = "D8DEE9" # Dark Foreground 
base05 = "E5E9F0" # Default Foreground
base06 = "ECEFF4" # Light Foreground
base07 = "8FBCBB" # Light Background
base08 = "BF616A" # red
base09 = "e04a13" # orange
base0A = "f29839" # yellow
base0B = "A3BE8C" # green
base0C = "88C0D0" # cyan
base0D = "B48EAD" # blue/accent
base0E = "5E81AC" # purple
base0F = "dc2f42" # brown

