# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-amd"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/6debce0d-7546-463a-a23f-44de31152fd8";
    fsType = "btrfs";
    options = ["subvol=@root"];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/6debce0d-7546-463a-a23f-44de31152fd8";
    fsType = "btrfs";
    options = ["subvol=@home"];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/B0AB-13E6";
    fsType = "vfat";
  };
  fileSystems."/home/strix/Media/Shared" = {
    device = "/dev/disk/by-uuid/7C6C14D619FC92DD";
    fsType = "ntfs3";
    options = [
      "uid=1000"
      "rw"
      "force"
    ];
  };

  swapDevices = [
    {device = "/dev/disk/by-uuid/3d2fe0dc-1b4b-4e76-a43d-3ce4462e6b63";}
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
