# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "ehci_pci" "ahci" "usb_storage" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/fb634582-8097-4b43-bb51-8adef8b82f70";
    fsType = "xfs";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/B358-F0A6";
    fsType = "vfat";
    options = ["fmask=0022" "dmask=0022"];
  };

  fileSystems."/hdd/git" = {
    device = "/dev/disk/by-uuid/fd108688-8255-4723-ac82-107b72cde9b4";
    fsType = "btrfs";
    options = ["subvol=@git"];
  };

  fileSystems."/hdd/nextcloud" = {
    device = "/dev/disk/by-uuid/fd108688-8255-4723-ac82-107b72cde9b4";
    fsType = "btrfs";
    options = ["subvol=@nextcloud"];
  };

  fileSystems."/hdd/public" = {
    device = "/dev/disk/by-uuid/fd108688-8255-4723-ac82-107b72cde9b4";
    fsType = "btrfs";
    options = ["subvol=@public"];
  };

  fileSystems."/hdd/private" = {
    device = "/dev/disk/by-uuid/fd108688-8255-4723-ac82-107b72cde9b4";
    fsType = "btrfs";
    options = ["subvol=@private"];
  };

  swapDevices = [];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp3s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp4s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
